/**
 * Lux key API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KeySubCategory } from './keySubCategory';
import { KeyPrice } from './keyPrice';
import { CarBrand } from './carBrand';
import { KeyBrand } from './KeyBrand';


export interface Key {
  id: number;
  amount: number;
  code: string;
  createdDate: string;
  lastModifiedDate: string;
  carBrands: CarBrand[];
  idCurrentPrice: KeyPrice;
  idKeyBrand: KeyBrand;
  idKeySubCategory: KeySubCategory;
  keyPrices: KeyPrice[];
}

