/**
 * Lux key API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {KeySubCategory} from './keySubCategory';
import {KeyPrice} from './keyPrice';
import {CarModel} from './carModel';


export interface Key {
  id: number;
  name: string;
  amount: number;
  code: string;
  createdDate: string;
  lastModifiedDate: string;
  idCarModel: CarModel;
  idCurrentPrice: KeyPrice;
  idKeySubCategory: KeySubCategory;
  keyPrices: KeyPrice[];
}

