/**
 * Lux key API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KeyCategory } from './keyCategory';
import { Key } from './key';


export interface KeySubCategory { 
    id: number;
    name: string;
    createdDate: string;
    lastModifiedDate: string;
    idCategory: KeyCategory;
    keys: Key;
}

